/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.MarioPizzelini;

public class AgregarPedidos extends javax.swing.JFrame {
    private MarioPizzelini empresa;
    private String rutEmpresa;

    //Constructor
    public AgregarPedidos(String rutEmpresa, MarioPizzelini empresa) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.empresa = empresa;
        this.rutEmpresa = rutEmpresa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelText2 = new javax.swing.JLabel();
        jLabelText3 = new javax.swing.JLabel();
        jLabelText4 = new javax.swing.JLabel();
        jLabelText5 = new javax.swing.JLabel();
        jLabelText6 = new javax.swing.JLabel();
        jLabelText7 = new javax.swing.JLabel();
        jLabelText8 = new javax.swing.JLabel();
        jLabelText9 = new javax.swing.JLabel();
        jLabelText10 = new javax.swing.JLabel();
        jbVolver = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbPizzas = new javax.swing.JButton();
        jTextRUT = new javax.swing.JTextField();
        jTextNOMBRE = new javax.swing.JTextField();
        jTextAPELLIDO = new javax.swing.JTextField();
        jTextFONO = new javax.swing.JTextField();
        jTextCANTPI = new javax.swing.JTextField();
        jTextCANTBE = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("AGREGAR PEDIDOS");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelText2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelText2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText2.setText("CANTIDAD BEBESTIBLES:");
        getContentPane().add(jLabelText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabelText3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelText3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText3.setText("Ingresar los datos del cliente para agregar el siguiente");
        getContentPane().add(jLabelText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabelText4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelText4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText4.setText("Ingresar los datos del pedido para el cliente:");
        getContentPane().add(jLabelText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabelText5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelText5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText5.setText("RUT:");
        getContentPane().add(jLabelText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabelText6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelText6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText6.setText("NOMBRE:");
        getContentPane().add(jLabelText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabelText7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelText7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText7.setText("APELLIDO:");
        getContentPane().add(jLabelText7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabelText8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelText8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText8.setText("pedido:");
        getContentPane().add(jLabelText8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabelText9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelText9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText9.setText("TELÉFONO:");
        getContentPane().add(jLabelText9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabelText10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelText10.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText10.setText("CANTIDAD PIZZAS:");
        getContentPane().add(jLabelText10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jbVolver.setBackground(new java.awt.Color(101, 48, 0));
        jbVolver.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbVolver.setForeground(new java.awt.Color(255, 255, 255));
        jbVolver.setText("Salir");
        jbVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jbVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 80, 30));

        jbCancelar.setBackground(new java.awt.Color(101, 48, 0));
        jbCancelar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jbCancelar.setText("Cancelar");
        getContentPane().add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jbPizzas.setBackground(new java.awt.Color(101, 48, 0));
        jbPizzas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbPizzas.setForeground(new java.awt.Color(255, 255, 255));
        jbPizzas.setText("Preparar Pizzas");
        getContentPane().add(jbPizzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        jTextRUT.setBackground(new java.awt.Color(51, 51, 51));
        jTextRUT.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextRUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 160, -1));

        jTextNOMBRE.setBackground(new java.awt.Color(51, 51, 51));
        jTextNOMBRE.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextNOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 120, -1));

        jTextAPELLIDO.setBackground(new java.awt.Color(51, 51, 51));
        jTextAPELLIDO.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextAPELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 120, -1));

        jTextFONO.setBackground(new java.awt.Color(51, 51, 51));
        jTextFONO.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 100, -1));

        jTextCANTPI.setBackground(new java.awt.Color(51, 51, 51));
        jTextCANTPI.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextCANTPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 110, -1));

        jTextCANTBE.setBackground(new java.awt.Color(51, 51, 51));
        jTextCANTBE.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextCANTBE, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 110, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/fondomod_opt_opt.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        MenuSucursal frame = new MenuSucursal(rutEmpresa,empresa);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbVolverActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelText10;
    private javax.swing.JLabel jLabelText2;
    private javax.swing.JLabel jLabelText3;
    private javax.swing.JLabel jLabelText4;
    private javax.swing.JLabel jLabelText5;
    private javax.swing.JLabel jLabelText6;
    private javax.swing.JLabel jLabelText7;
    private javax.swing.JLabel jLabelText8;
    private javax.swing.JLabel jLabelText9;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextAPELLIDO;
    private javax.swing.JTextField jTextCANTBE;
    private javax.swing.JTextField jTextCANTPI;
    private javax.swing.JTextField jTextFONO;
    private javax.swing.JTextField jTextNOMBRE;
    private javax.swing.JTextField jTextRUT;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbPizzas;
    private javax.swing.JButton jbVolver;
    // End of variables declaration//GEN-END:variables
}
