/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author XavierKrostya
 */
public class MenuSucursal extends javax.swing.JFrame {

    /**
     * Creates new form MenuSucursal
     */
    public MenuSucursal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jbSalir = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelRUT = new javax.swing.JLabel();
        jLabelText1 = new javax.swing.JLabel();
        jLabelcon = new javax.swing.JLabel();
        jbPedidos = new javax.swing.JButton();
        jbInventario = new javax.swing.JButton();
        jbCerrarSesion = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbSalir.setBackground(new java.awt.Color(101, 48, 0));
        jbSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbSalir.setText("Salir");
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 70, 30));

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("MENÚ SUCURSAL");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelRUT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelRUT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRUT.setText("12.345.678-9");
        getContentPane().add(jLabelRUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabelText1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelText1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText1.setText("RUT de la sucursal:");
        getContentPane().add(jLabelText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabelcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/coloreslmini_opt.png"))); // NOI18N
        getContentPane().add(jLabelcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jbPedidos.setBackground(new java.awt.Color(101, 48, 0));
        jbPedidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbPedidos.setForeground(new java.awt.Color(255, 255, 255));
        jbPedidos.setText("Pedidos");
        getContentPane().add(jbPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 260, -1));

        jbInventario.setBackground(new java.awt.Color(101, 48, 0));
        jbInventario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbInventario.setForeground(new java.awt.Color(255, 255, 255));
        jbInventario.setText("Inventario");
        getContentPane().add(jbInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 260, -1));

        jbCerrarSesion.setBackground(new java.awt.Color(101, 48, 0));
        jbCerrarSesion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setText("Cerrar sesión");
        getContentPane().add(jbCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 260, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/fondoop_opt.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSucursal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelRUT;
    private javax.swing.JLabel jLabelText1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelcon;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JButton jbCerrarSesion;
    private javax.swing.JButton jbInventario;
    private javax.swing.JButton jbPedidos;
    private javax.swing.JButton jbSalir;
    // End of variables declaration//GEN-END:variables
}
