/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.MarioPizzelini;

public class MenuSucursal extends javax.swing.JFrame {
    private MarioPizzelini empresa;
    private String rutActual;
    
    //Constructor
    public MenuSucursal(String rutActual, MarioPizzelini empresa) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.empresa = empresa;
        jLabelRUT.setText(rutActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jbSalir = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelRUT = new javax.swing.JLabel();
        jLabelMONTO = new javax.swing.JLabel();
        jLabelcon = new javax.swing.JLabel();
        jbPedidos = new javax.swing.JButton();
        jbInventario = new javax.swing.JButton();
        jbCerrarSesion = new javax.swing.JButton();
        jLabelText2 = new javax.swing.JLabel();
        jLabelText3 = new javax.swing.JLabel();
        jLabelText4 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbSalir.setBackground(new java.awt.Color(101, 48, 0));
        jbSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbSalir.setText("Salir");
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 70, 30));

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("MENÚ SUCURSAL");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelRUT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelRUT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRUT.setText("12.345.678-9");
        getContentPane().add(jLabelRUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabelMONTO.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelMONTO.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMONTO.setText("12345");
        getContentPane().add(jLabelMONTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 110, -1));

        jLabelcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/coloreslmini_opt.png"))); // NOI18N
        getContentPane().add(jLabelcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jbPedidos.setBackground(new java.awt.Color(101, 48, 0));
        jbPedidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbPedidos.setForeground(new java.awt.Color(255, 255, 255));
        jbPedidos.setText("Pedidos");
        getContentPane().add(jbPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 130, -1));

        jbInventario.setBackground(new java.awt.Color(101, 48, 0));
        jbInventario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbInventario.setForeground(new java.awt.Color(255, 255, 255));
        jbInventario.setText("Inventario");
        getContentPane().add(jbInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 130, -1));

        jbCerrarSesion.setBackground(new java.awt.Color(101, 48, 0));
        jbCerrarSesion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setText("Cerrar sesión");
        jbCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jbCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 130, -1));

        jLabelText2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelText2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText2.setText("RUT de la sucursal:");
        getContentPane().add(jLabelText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabelText3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelText3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText3.setText("Recaudación total:");
        getContentPane().add(jLabelText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabelText4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelText4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText4.setText("$");
        getContentPane().add(jLabelText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 10, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/fondoop_opt.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Al clickear se saldrá del programa
    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarSesionActionPerformed
        SeleccionSucursal frame = new SeleccionSucursal(empresa);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbCerrarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelMONTO;
    private javax.swing.JLabel jLabelRUT;
    private javax.swing.JLabel jLabelText2;
    private javax.swing.JLabel jLabelText3;
    private javax.swing.JLabel jLabelText4;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelcon;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JButton jbCerrarSesion;
    private javax.swing.JButton jbInventario;
    private javax.swing.JButton jbPedidos;
    private javax.swing.JButton jbSalir;
    // End of variables declaration//GEN-END:variables
}
