/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.MarioPizzelini;

public class MenuInventario extends javax.swing.JFrame {
    private MarioPizzelini empresa;
    private String rutEmpresa;

    //Constructor
    public MenuInventario(String rutEmpresa, MarioPizzelini empresa) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.empresa = empresa;
        this.rutEmpresa = rutEmpresa;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jbVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbIngredientes = new javax.swing.JButton();
        jbBebestibles = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("INVENTARIO SUCURSAL");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jbVolver.setBackground(new java.awt.Color(101, 48, 0));
        jbVolver.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbVolver.setForeground(new java.awt.Color(255, 255, 255));
        jbVolver.setText("Volver");
        jbVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jbVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/inventario-icon_opt.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jbIngredientes.setBackground(new java.awt.Color(101, 48, 0));
        jbIngredientes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbIngredientes.setForeground(new java.awt.Color(255, 255, 255));
        jbIngredientes.setText("Ingredientes");
        jbIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngredientesActionPerformed(evt);
            }
        });
        getContentPane().add(jbIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 260, -1));

        jbBebestibles.setBackground(new java.awt.Color(101, 48, 0));
        jbBebestibles.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbBebestibles.setForeground(new java.awt.Color(255, 255, 255));
        jbBebestibles.setText("Bebestibles");
        jbBebestibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBebestiblesActionPerformed(evt);
            }
        });
        getContentPane().add(jbBebestibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 260, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/fondoop_opt.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        MenuSucursal frame = new MenuSucursal(rutEmpresa,empresa);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbVolverActionPerformed

    private void jbBebestiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBebestiblesActionPerformed
        MenuIngredientes frame = new MenuIngredientes(rutEmpresa,empresa);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbBebestiblesActionPerformed

    private void jbIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngredientesActionPerformed
        MenuBebestibles frame = new MenuBebestibles();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbIngredientesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JButton jbBebestibles;
    private javax.swing.JButton jbIngredientes;
    private javax.swing.JButton jbVolver;
    // End of variables declaration//GEN-END:variables
}
