/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.Cliente;
import clases.MarioPizzelini;
import clases.Sucursal;
import javax.swing.JOptionPane;

public class SeleccionSucursal extends javax.swing.JFrame {
    private MarioPizzelini empresa;
    private int montoTotal;
    private int montoTotalSucursal;
    private Sucursal sucursalMasRecaudada;
    private Cliente clienteConMasPedidos;
    
    //Constructor
    public SeleccionSucursal(MarioPizzelini empresa) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.empresa = empresa;
        ingresarMontoGeneral();
        ingresarSucursal();
        ingresarCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSalir = new javax.swing.JButton();
        jLabelcon = new javax.swing.JLabel();
        jbAgregar = new javax.swing.JButton();
        jTextRut = new javax.swing.JTextField();
        jLabelText2 = new javax.swing.JLabel();
        jLabelText = new javax.swing.JLabel();
        jLabelText1 = new javax.swing.JLabel();
        jLabelMONTOSUCURSAL = new javax.swing.JLabel();
        jLabelNOMBRECLIENTE = new javax.swing.JLabel();
        jLabelDIRECCION = new javax.swing.JLabel();
        jLabelText6 = new javax.swing.JLabel();
        jLabelText7 = new javax.swing.JLabel();
        jLabelMONTOEMPRESA = new javax.swing.JLabel();
        jLabelText9 = new javax.swing.JLabel();
        jLabelText10 = new javax.swing.JLabel();
        jLabelRUTCLIENTE = new javax.swing.JLabel();
        jbIngresar = new javax.swing.JButton();
        jbMostrar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbSalir.setBackground(new java.awt.Color(101, 48, 0));
        jbSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbSalir.setText("Volver");
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 80, 30));

        jLabelcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/sucursales-icono_opt.png"))); // NOI18N
        getContentPane().add(jLabelcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jbAgregar.setBackground(new java.awt.Color(101, 48, 0));
        jbAgregar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 160, -1));

        jTextRut.setBackground(new java.awt.Color(51, 51, 51));
        jTextRut.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 190, -1));

        jLabelText2.setBackground(new java.awt.Color(51, 51, 51));
        jLabelText2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelText2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText2.setText("RUT:");
        getContentPane().add(jLabelText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabelText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText.setText("$");
        getContentPane().add(jLabelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        jLabelText1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelText1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText1.setText("Ingrese el RUT de alguna sucursal:");
        getContentPane().add(jLabelText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabelMONTOSUCURSAL.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelMONTOSUCURSAL.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMONTOSUCURSAL.setText("12345");
        getContentPane().add(jLabelMONTOSUCURSAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jLabelNOMBRECLIENTE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelNOMBRECLIENTE.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNOMBRECLIENTE.setText("nombre del cliente");
        getContentPane().add(jLabelNOMBRECLIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabelDIRECCION.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelDIRECCION.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDIRECCION.setText("direccion");
        getContentPane().add(jLabelDIRECCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabelText6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelText6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText6.setText("Recaudación de MarioPizzelini:");
        getContentPane().add(jLabelText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabelText7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelText7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText7.setText("$");
        getContentPane().add(jLabelText7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabelMONTOEMPRESA.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelMONTOEMPRESA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMONTOEMPRESA.setText("12345");
        getContentPane().add(jLabelMONTOEMPRESA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabelText9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelText9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText9.setText("Sucursal con mayor recaudación:");
        getContentPane().add(jLabelText9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabelText10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelText10.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText10.setText("Cliente con más pedidos:");
        getContentPane().add(jLabelText10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabelRUTCLIENTE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelRUTCLIENTE.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRUTCLIENTE.setText("12.345.678-9");
        getContentPane().add(jLabelRUTCLIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jbIngresar.setBackground(new java.awt.Color(101, 48, 0));
        jbIngresar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jbIngresar.setText("Ingresar");
        jbIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jbIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 160, -1));

        jbMostrar.setBackground(new java.awt.Color(101, 48, 0));
        jbMostrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbMostrar.setForeground(new java.awt.Color(255, 255, 255));
        jbMostrar.setText("Mostrar Sucursales");
        jbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 160, -1));

        jbEliminar.setBackground(new java.awt.Color(101, 48, 0));
        jbEliminar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 160, -1));

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("INGRESAR A SUCURSAL");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/fondomod_opt_opt.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ingresarMontoGeneral(){
        montoTotal = empresa.recaudacionTotal();
        jLabelMONTOEMPRESA.setText(Integer.toString(montoTotal));
    }
    
    private void ingresarSucursal(){
        sucursalMasRecaudada = empresa.sucursalConMayorRecaudacion();
        montoTotalSucursal = sucursalMasRecaudada.valorTotalPedidosSucursal();
        
        if(sucursalMasRecaudada == null){
            jLabelDIRECCION.setText("Ninguna");
            jLabelMONTOSUCURSAL.setText("0");
        }
        else{
            jLabelDIRECCION.setText(sucursalMasRecaudada.getDireccion());
            jLabelMONTOSUCURSAL.setText(Integer.toString(montoTotalSucursal));
        }
    }
    
    private void ingresarCliente(){
        clienteConMasPedidos = empresa.buscarClienteConMasPedidos();
        
        if(clienteConMasPedidos == null){
            jLabelNOMBRECLIENTE.setText("Ninguno");
            jLabelRUTCLIENTE.setText("");
        }
        else{
            jLabelNOMBRECLIENTE.setText(clienteConMasPedidos.getNombre());
            jLabelRUTCLIENTE.setText(clienteConMasPedidos.getRut());
        }
    }
    
    //Al clickear el botón volver
    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        Inicio frame = new Inicio(empresa);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed
    
    //Al clickear el botón para agregar una sucursal
    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        AgregarSucursal frame = new AgregarSucursal(empresa);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbAgregarActionPerformed
    
    //Al clickear el botón para eliminar una sucursal
    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        if(empresa.estaVacioSucursales()){
            JOptionPane.showMessageDialog(null, "¡No hay sucursales por eliminar!");
        }
        else{
            EliminarSucursal frame = new EliminarSucursal(empresa);
            frame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jbEliminarActionPerformed
    
    //Al clickear el botón para mostrar por consola todas las sucursales
    private void jbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarActionPerformed
        if(empresa.estaVacioSucursales()){
            JOptionPane.showMessageDialog(null, "¡No hay sucursales por mostrar!");
        }
        else{
            empresa.mostrarSucursales();
        }
    }//GEN-LAST:event_jbMostrarActionPerformed

    //Al clickear el botón, ingresarás al frame del menu sucursal
    private void jbIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngresarActionPerformed
        String rut = jTextRut.getText();
        
        if(!rut.equals("")){
            if(empresa.buscarSucursalPorRut(rut) != null){
                MenuSucursal frame = new MenuSucursal(rut,empresa);
                frame.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "¡RUT no encontrado!");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "¡RUT no valido!");
        }
    }//GEN-LAST:event_jbIngresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDIRECCION;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelMONTOEMPRESA;
    private javax.swing.JLabel jLabelMONTOSUCURSAL;
    private javax.swing.JLabel jLabelNOMBRECLIENTE;
    private javax.swing.JLabel jLabelRUTCLIENTE;
    private javax.swing.JLabel jLabelText;
    private javax.swing.JLabel jLabelText1;
    private javax.swing.JLabel jLabelText10;
    private javax.swing.JLabel jLabelText2;
    private javax.swing.JLabel jLabelText6;
    private javax.swing.JLabel jLabelText7;
    private javax.swing.JLabel jLabelText9;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelcon;
    private javax.swing.JTextField jTextRut;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbIngresar;
    private javax.swing.JButton jbMostrar;
    private javax.swing.JButton jbSalir;
    // End of variables declaration//GEN-END:variables
}
